global:
  slack_api_url: "https://hooks.slack.com/services/<SLACK_API_URL>"
route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      alertname: InstanceDown
  receiver: 'alert-team'
receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "#prometheus-alerts"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"